### ISSUE TITLE
Compile error super-intel.c

### ISSUE THREAD

**Issue by gene-git** [md-raid-utilities/mdadm#67]
Building git master on archlinux I get the error shown below.

git bisect lands on this commit as triggering:

93c5215677a71e9772f68a449533cb3c97d2b869 is the first bad commit
commit 93c5215677a71e9772f68a449533cb3c97d2b869 (HEAD)
Author: Kinga Stefaniuk <kinga.stefaniuk@intel.com>
Date:   Thu Jul 4 15:01:06 2024 +0200

    Makefile: add more compiler flags
    
    It is essential to avoid vulnerabilities in code as much
    as possible using safe compilation flags. It is easier if
    they are added to the Makefile and applied during compilation.
    Add new gcc flags and make them configurable, because they
    may not be supported for some compilers.
    Set FORTIFY_SOURCE with the highest supported value for platform.
    
    Signed-off-by: Kinga Stefaniuk <kinga.stefaniuk@intel.com>

Toolchain:

```
gcc 14.1.1+r309+gbb34b7eda1f-1
binutils 2.42+r195+g29ae8b8ea71-1
```

Error output

```
gcc -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIE -Warray-bounds -Wimplicit-fallthrough=0 -Wformat-overflow -Wstringop-overflow -fno-strict-overflow -fno-delete-null-pointer-checks -fwrapv -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE -DSendmail=\""/usr/sbin/sendmail -t"\" -DCONFFILE=\"/etc/mdadm.conf\" -DCONFFILE2=\"/etc/mdadm/mdadm.conf\" -DMAP_DIR=\"/run/mdadm\" -DMAP_FILE=\"map\" -DMDMON_DIR=\"/run/mdadm\" -DFAILED_SLOTS_DIR=\"/run/mdadm/failed-slots\" -DNO_COROSYNC -DNO_DLM -DVERSION=\"4.3-135-g87f96c87\" -DVERS_DATE="\"2024-07-30\""  -DUSE_PTHREADS -DBINDIR=\"/sbin\"  -o super-intel.
o -c super-intel.c
super-intel.c: In function ‘end_migration’:
super-intel.c:4360:29: error: writing 2 bytes into a region of size 0 [-Werror=stringop-overflow=]
 4360 |         dev->vol.migr_state = 0;
      |         ~~~~~~~~~~~~~~~~~~~~^~~
cc1: note: destination object is likely at address zero
cc1: all warnings being treated as errors
make: *** [Makefile:232: super-intel.o] Error 1
```

**Comment by mtkaczyk** [comment]
@ktanska please take a look.

**Comment by ktanska** [comment]
Hi @gene-git 
thanks for your report. While working on your issue, I've realized that our review.yml contains wrong configuration and do not update gcc version correctly. 
Please review #68 and confirm if it fixes your issue.

Regards,
Kinga

**Comment by gene-git** [comment]
Thank you - confirm this fixes it.

**Comment by gene-git** [comment]
What are your thoughts about when you might push this to git master ?  I'm not pushing at all,  just curious about timing.

thanks again for fixing.

**Comment by gene-git** [comment]
Reopening pending completion of https://github.com/md-raid-utilities/mdadm/pull/68

**Comment by mtkaczyk** [comment]
Closing, pull merged. Thanks!
